spring:
  application:
    name: product

  datasource:
    url: jdbc:mysql://localhost:3306/ProductDB
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
#      don't use 'create' in production, it will drop existing data
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: false

server:
  port: 8081

